name: calculator
version: '1.0.0'
summary: Solve simple equations
description: |
  A simple calculator for everyday use. It supports basic and some
  scientific calculations including trigonometry functions, sin, cos, and tan.

grade: stable
confinement: devmode

apps:
  calculator:
    command: desktop-launch $SNAP/usr/bin/io.elementary.calculator
    plugs:
      - x11
      - gsettings
      - opengl

parts:
  elementary:
    plugin: nil
    prepare: |
      add-apt-repository -y ppa:elementary-os/stable
      add-apt-repository -y ppa:elementary-os/os-patches
      echo "Package: *" > /etc/apt/preferences.d/elementary-stable
      echo "Pin: release o=LP-PPA-elementary-os-stable" >> /etc/apt/preferences.d/elementary-stable
      echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-stable
      echo "Package: *" > /etc/apt/preferences.d/elementary-patches
      echo "Pin: release o=LP-PPA-elementary-os-os-patches" >> /etc/apt/preferences.d/elementary-patches
      echo "Pin-Priority: 1000" >> /etc/apt/preferences.d/elementary-patches
      apt update
      apt dist-upgrade -y
  calculator:
    after: [elementary, desktop-gtk3]
    plugin: meson
    meson-parameters: [--prefix=/usr]
    source: .
    build-packages:
      - build-essential
      - gettext
      - libgee-0.8-dev
      - libgtk-3-dev
      - valac
      - libgranite-dev
      - desktop-file-utils
      - appstream
    organize:
      share/glib-2.0: usr/share/glib-2.0
