---

name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest

    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions:elementary-juno
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions@master
        with:
          bundle: calculator.flatpak
          manifest-path: io.elementary.calculator.yml
          run-tests: true
          repository-name: elementary
          repository-url: https://flatpak.elementary.io/elementary.flatpakrepo
          cache-key: flatpak

  lint:
    name: Lint
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: io.elementary.vala-lint -d .
